### ISSUE TITLE
python-pypi2pkgbuild build error

### ISSUE THREAD

**Issue by hexec** [SirToffski/Arch-GNS3-Helper#1]
The command:  
`pypi2pkgalias git+file://$PWD`

Returns error:
```
Cloning into 'gns3-server'...
remote: Enumerating objects: 45435, done.
remote: Counting objects: 100% (45435/45435), done.
remote: Compressing objects: 100% (8453/8453), done.
remote: Total 45435 (delta 36663), reused 45435 (delta 36663)
Receiving objects: 100% (45435/45435), 26.72 MiB | 35.86 MiB/s, done.
Resolving deltas: 100% (36663/36663), done.
Traceback (most recent call last):
  File "/usr/bin/pypi2pkgbuild.py", line 1477, in <module>
    sys.exit(main())
  File "/usr/bin/pypi2pkgbuild.py", line 1454, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/bin/pypi2pkgbuild.py", line 1253, in create_package
    pkg = dispatch_package_builder(name, options)
  File "/usr/bin/pypi2pkgbuild.py", line 1245, in dispatch_package_builder
    ref = PackageRef(
  File "/usr/bin/pypi2pkgbuild.py", line 695, in __init__
    self.info = _get_info(
  File "/usr/bin/pypi2pkgbuild.py", line 601, in _get_info
    info = locals()[f"_get_info_{source}"]()
  File "/usr/bin/pypi2pkgbuild.py", line 542, in _get_info_git
    metadata = _get_metadata(
  File "/usr/bin/pypi2pkgbuild.py", line 505, in _get_metadata
    "CFLAGS": get_makepkg_conf()["CFLAGS"],
KeyError: 'CFLAGS'
```

---

Any ideas to get past this issue would be awesome :)

**Comment by LaumiH** [comment]
In case anyone has the same issue: replace `python-pypi2pkgbuild` with `python-pypi2pkgbuild-git` during the installation process and it worked for me :)
